Repository fipl-hse/2021-2-level-labs, pull requests merged in 2021-11, with the labels that each got.

#113 Laboratory work #2, Pareshina Evgeniya - 20FPL2
  .gitignore
  lab_2/main.py
  lab_2/start.py
  lab_2/target_score.txt
Labels: Done, Approved

#142 [LAB 3] [skip-name] Unittests
  automation/lab_3/target_tests_10.txt
  automation/lab_3/target_tests_4.txt
  automation/lab_3/target_tests_6.txt
  automation/lab_3/target_tests_8.txt
  automation/labs.txt
  lab_1/detect_language_advanced_test.py
  lab_2/main.py
  lab_3/calculate_distance_ngrams_test.py
  lab_3/calculate_distance_test.py
  lab_3/calculate_log_probabilities_test.py
  lab_3/calculate_probability_test.py
  lab_3/decode_corpus_test.py
  lab_3/encode_corpus_test.py
  lab_3/extract_n_grams_frequencies_test.py
  lab_3/extract_n_grams_log_probabilities_test.py
  lab_3/fill_ngram_storage_bigrams_test.py
  lab_3/fill_ngram_storage_fivegrams_test.py
  lab_3/fill_ngram_storage_threegrams_test.py
  lab_3/get_n_gram_frequencies_test.py
  lab_3/get_threegram_frequencies_test.py
  lab_3/get_top_k_bigrams_test.py
  lab_3/get_top_k_threegrams_test.py
  lab_3/lab_3.md
  lab_3/language_detector_test.py
  lab_3/language_profile_bigrams_test.py
  lab_3/language_profile_ngrams_test.py
  lab_3/letter_storage_test.py
  lab_3/probability_language_detector_test.py
  lab_3/profile_sample.json
  lab_3/sample_profile.json
  lab_3/save_and_open_profile_test.py
  lab_3/tokenize_by_sentence_test.py
  lab_3/working_with_profile_test.py
Labels: enhancement

#146 [CI] [skip-name] New update strategies
  .github/workflows/update-fork.yml
  automation/github/update-fork.sh
Labels: enhancement

#173 [LAB 3] [skip-name] Fix unittests
  lab_3/calculate_log_probabilities_test.py
  lab_3/calculate_probability_test.py
  lab_3/get_n_gram_frequencies_test.py
  lab_3/get_threegram_frequencies_test.py
  lab_3/language_profile_ngrams_test.py
  lab_3/probability_language_detector_test.py
  lab_3/tokenize_by_sentence_test.py
  lab_3/working_with_profile_test.py
Labels: Review required

#150 Laboratory work #3, Zakirova Karina - 20FPL1
  lab_3/main.py
  lab_3/probability_language_detector_test.py
  lab_3/start.py
  lab_3/target_score.txt
Labels: Approved

#189 [skip-name] [LAB 3] [CI] Enable tests for the fourth lab in CI & Fix Lab 3 realization and tests
  automation/labs.txt
  lab_3/lab_3.md
  lab_3/main.py
  lab_3/probability_language_detector_test.py
Labels: enhancement
