Repository fipl-hse/2021-2-level-labs, pull requests merged in 2021-12, with the labels that each got.

#242 [LAB 4] [skip-name] Account for unigrams in likelihood tests
  lab_4/likelihood_text_generator_test.py
Labels: tests

#251 [CI] [skip-name] Extend timeout for jobs
  .github/workflows/inspect-code.yml
Labels: CI

#253 [skip-name] Skip Python temporary files in .gitignore
  .gitignore
Labels: code

#241 Laboratory work #4, Tatarinov Maxim - 20FPL3
  lab_4/main.py
  lab_4/start.py
  lab_4/target_score.txt
Labels: Done

#268 [skip-name] [CI] Add missing seminar title. Fail CI if lint check fails
  README.md
  automation/check_lint.py
  automation/run-lint.sh
  lab_1/start.py
Labels: CI
